src/main/java/com/smartbear/postman/PostmanImporter.java
src/test/java/com/smartbear/postman/PostmanImporterTest.java

https://smartbear.atlassian.net/browse/SOAP-5917

SOAP-5917 Use original requests name from collection

---

src/main/java/com/smartbear/postman/PostmanImporter.java
src/test/java/com/smartbear/postman/PostmanImporterTest.java

https://smartbear.atlassian.net/browse/RIA-654

RIA-654-Wsdl excess messages fix

---

src/main/java/com/smartbear/postman/ImportPostmanCollectionAction.java
src/main/java/com/smartbear/postman/PostmanImporter.java
src/main/java/com/smartbear/postman/VariableUtils.java
src/main/java/com/smartbear/postman/script/AddEqualsAssertionCommand.java
src/main/java/com/smartbear/postman/script/PostmanScriptParser.java
src/main/java/com/smartbear/postman/script/PostmanScriptTokenizer.java
src/test/java/com/smartbear/postman/script/PostmanScriptParserTest.java

Changes to make it work with SoapUI OS 5.3

SOAPUIOS-208 SoapUI OS integration

---

src/main/java/com/smartbear/postman/PostmanImporter.java
src/main/java/com/smartbear/postman/script/SetGlobalVariableCommand.java

https://smartbear.atlassian.net/browse/RIA-4287

RIA-4287 Fixes for creating project properties from postman properties

---

src/main/java/com/smartbear/postman/PostmanImporter.java

https://smartbear.atlassian.net/browse/RIA-4760

RIA-4760 Rename analytics action

---

src/main/java/com/smartbear/postman/PostmanImporter.java

https://smartbear.atlassian.net/browse/RIA-4982

RIA-4982 Define SourceModule as "Any"

---

pom.xml
src/main/java/com/smartbear/postman/PostmanImporter.java
src/main/java/com/smartbear/postman/VariableUtils.java
src/main/java/com/smartbear/postman/script/SetGlobalVariableCommand.java
src/test/java/com/smartbear/postman/PostmanImporterTest.java
src/test/resources/Parameterized_Endpoint_Collection.postman_collection

https://smartbear.atlassian.net/browse/RIA-7079
@antone-sb plese merge https://github.com/SmartBear/readyapi-free-os/pull/629 before

RIA-7079 Improvement for importing requests whose urls are parameterized by postman variables

---

pom.xml
src/main/templates/com/smartbear/postman/PluginConfig.java

https://smartbear.atlassian.net/browse/RIA-7249

RIA-7249 Change minimumReadyApiVersion for postman plugin and fix unit tests

---

pom.xml

Do not move the issue.
https://smartbear.atlassian.net/browse/RIA-8342

RIA-8342 Added missing dependency

---

pom.xml
src/main/java/com/smartbear/postman/PostmanImporter.java
src/main/java/com/smartbear/postman/VariableUtils.java
src/main/java/com/smartbear/postman/collection/PostmanCollection.java
src/main/java/com/smartbear/postman/collection/PostmanCollectionFactory.java
src/main/java/com/smartbear/postman/collection/PostmanCollectionV1.java
src/main/java/com/smartbear/postman/collection/PostmanCollectionV2.java
src/main/templates/com/smartbear/postman/PluginConfig.java
src/test/java/com/smartbear/postman/DummyTestCreator.java
src/test/java/com/smartbear/postman/PostmanImporterTest.java
src/test/resources/New_Methods_Collection.postman_collection_v2.1
src/test/resources/Postman_Echo.postman_collection_v2.0
src/test/resources/Postman_Echo.postman_collection_v2.1
src/test/resources/REST_Get.postman_collection_v2.0.json
src/test/resources/REST_Get_Collection.postman_collection_v2.0
src/test/resources/REST_Get_Collection.postman_collection_v2.1
src/test/resources/REST_Post_Collection.postman_collection_v2.0
src/test/resources/REST_Post_Collection.postman_collection_v2.1
src/test/resources/SOAP_Collection.postman_collection_v2.0
src/test/resources/SOAP_Collection.postman_collection_v2.1

https://smartbear.atlassian.net/browse/RIA-6640

RIA-6640 New postman collection versions

---

src/main/java/com/smartbear/postman/ImportPostmanCollectionAction.java
src/main/java/com/smartbear/postman/PostmanImporter.java

https://smartbear.atlassian.net/browse/RIA-9504

RIA-9504 Support importing postman collections from http(s)

---

src/main/java/com/smartbear/postman/ImportPostmanCollectionAction.java
src/main/java/com/smartbear/postman/PostmanImportMethodFactory.java
src/main/templates/com/smartbear/postman/PluginConfig.java

https://smartbear.atlassian.net/browse/RIA-7237

RIA-7237 - Enhance Postman import functionality

---

pom.xml
src/main/java/com/smartbear/postman/PostmanImporter.java
src/main/java/com/smartbear/postman/collection/PostmanCollection.java
src/main/java/com/smartbear/postman/collection/PostmanCollectionV1.java
src/main/java/com/smartbear/postman/collection/PostmanCollectionV2.java

https://smartbear.atlassian.net/browse/RIA-14907

Ria-14907 Create project variables from variable section

---

src/main/java/com/smartbear/postman/ImportPostmanCollectionAction.java

https://smartbear.atlassian.net/browse/RIA-13389

RIA-13389 - Show correct error message

---

pom.xml
src/assembly/dist-assembly.xml

Used renamed descriptor from https://maven.apache.org/plugins/maven-assembly-plugin/descriptor-refs.html#jar-with-dependencies

Custom assembly file

---

pom.xml
src/main/java/com/smartbear/postman/collection/PostmanCollection.java

https://smartbear.atlassian.net/browse/RIA-9607

RIA-9607 Fix multiline v2

---

pom.xml

https://smartbear.atlassian.net/browse/RIA-17949

RIA-17949 Bump to the release version

---

pom.xml

Don't move the task.
https://smartbear.atlassian.net/browse/RIA-17949

RIA-17949 HTTPS for repo address

---

src/main/java/com/smartbear/postman/GuiTestCreator.java
src/main/java/com/smartbear/postman/PostmanImporter.java
src/main/java/com/smartbear/postman/TestCreator.java
src/main/java/com/smartbear/postman/collection/PostmanCollection.java
src/main/java/com/smartbear/postman/collection/PostmanCollectionV1.java
src/main/java/com/smartbear/postman/collection/PostmanCollectionV2.java
src/test/java/com/smartbear/postman/DummyTestCreator.java
src/test/java/com/smartbear/postman/PostmanImporterTest.java
src/test/resources/GraphQL_Collection.postman_collection_v2.0

https://smartbear.atlassian.net/browse/RIA-19161

RIA-19161 Import collections with GraphQL

---

pom.xml

https://smartbear.atlassian.net/browse/RIA-21057

RIA-21057 Update ReadyAPI version to 3.47.0 and it's dependencies

---

pom.xml
src/test/java/com/smartbear/ready/plugin/postman/ImportPostmanCollectionActionTest.java
src/test/java/com/smartbear/ready/plugin/postman/PostmanImporterTest.java
src/test/java/com/smartbear/ready/plugin/postman/collection/PostmanCollectionFactoryTest.java
src/test/java/com/smartbear/ready/plugin/postman/script/PostmanScriptParserTest.java
src/test/java/com/smartbear/ready/plugin/postman/utils/GraphQLImporterUtilsTest.java
src/test/java/com/smartbear/ready/plugin/postman/utils/RestServiceCreatorTest.java
src/test/java/com/smartbear/ready/plugin/postman/utils/SoapServiceCreatorTest.java

https://smartbear.atlassian.net/browse/RIA-21403

RIA-21403 java 17 and dependencies update

---

pom.xml
readme.md

https://smartbear.atlassian.net/browse/RIA-22503

Release 3.0.1

---

pom.xml
src/main/java/com/smartbear/ready/plugin/postman/collection/PostmanCollectionFactory.java
src/test/java/com/smartbear/ready/plugin/postman/PostmanImporterTest.java
src/test/resources/Postman_Echo.postman_collection_v2.1

RIA-24788 Make unit tests run in Maven

---

pom.xml
src/test/java/com/smartbear/ready/plugin/postman/PostmanImporterTest.java
src/test/resources/SOAP_Collection.postman_collection
src/test/resources/SOAP_Collection.postman_collection_v2.0
src/test/resources/SOAP_Collection.postman_collection_v2.1
src/test/resources/SOAP_Collection_events.postman_collection_v2.1
src/test/resources/soap/public_soap_apis/Service1.asmx

Enables Postman collection tests (WSDL import part).

RIA-24788 Fix WSDL import tests

---

src/main/java/com/smartbear/ready/plugin/postman/PostmanImporter.java
src/main/java/com/smartbear/ready/plugin/postman/VariableUtils.java
src/main/java/com/smartbear/ready/plugin/postman/utils/PostmanCollectionUtils.java
src/main/java/com/smartbear/ready/plugin/postman/utils/VaultVariableResolver.java
src/test/java/com/smartbear/ready/plugin/postman/utils/PostmanCollectionUtilsTest.java
src/test/resources/utils/collection_with_unsupported_version.json
src/test/resources/utils/collection_with_vault_variables_V20.json
src/test/resources/utils/collection_with_vault_variables_V21.json

https://smartbear.atlassian.net/browse/RIA-23712

RIA-23712 Vault variable resolution

---

src/main/java/com/smartbear/ready/plugin/postman/utils/RestServiceCreator.java
src/test/java/com/smartbear/ready/plugin/postman/authorization/AuthorizationProfileImporterTest.java
src/test/java/com/smartbear/ready/plugin/postman/utils/RestServiceCreatorTest.java
src/test/resources/rest/multipart_collection.json

https://smartbear.atlassian.net/browse/RIA-9580

RIA-9580 encode query parameters

---

src/main/java/com/smartbear/ready/plugin/postman/PostmanImporter.java
src/main/java/com/smartbear/ready/plugin/postman/script/GetGlobalVariableCommand.java
src/main/java/com/smartbear/ready/plugin/postman/utils/GraphQLImporterUtils.java
src/main/java/com/smartbear/ready/plugin/postman/utils/RestServiceCreator.java
src/main/java/com/smartbear/ready/plugin/postman/utils/SoapServiceCreator.java
src/main/java/com/smartbear/ready/plugin/postman/utils/VariableUtils.java
src/test/java/com/smartbear/ready/plugin/postman/utils/VariableUtilsTest.java

https://smartbear.atlassian.net/browse/RIA-9585

RIA-9585 Dynamic variables parsing fix
